### ISSUE TITLE
LeagueV4, getting all ranks summoner

### ISSUE THREAD

**Issue by kaaiss** [MingweiSamuel/Camille#10]
how i can get all summoner ranks? previously i was using api.LeagueV4.GetLeagueEntriesForSummonerAsync(Region.EUNE, nick);
but it doesn't work now, I also can't find GetAllLeaguePositionsForSummonerAsync
![5252](https://user-images.githubusercontent.com/47061021/60775670-b55acf00-a125-11e9-9473-faf5a7ed18b8.JPG)

**Comment by MingweiSamuel** [comment]
Around 8 months ago the API was changed to take encrypted summoner IDs rather than numeric ones ([link](https://www.riotgames.com/en/DevRel/player-universally-unique-identifiers-and-a-new-security-layer)), if "previously" was that long ago.

The correct code should be something like this, where you pass in summoner ID rather than nick
```
string nick = "durirzad";
Summoner summoner = await api.SummonerV4.GetBySummonerNameAsync(nick);
LeagueEntry[] rankInfos = api.LeagueV4.GetLeagueEntriesForSummonerAsync(summoner.id); // encrypted summoner id
```

**Comment by MingweiSamuel** [comment]
It is strange though, I would expect it to throw an exception if you passed in a nick rather than id. Can I see your source code?

**Comment by kaaiss** [comment]
damn i forgot about this, my bad
I was using requesting api.LeagueV4.GetLeagueEntriesForSummonerAsync(nick) instead of summoner.id
Thank you very much and there you go, my code
        static async Task<Profile> GetProfileInfo(string nick, string region)
```
        static async Task<Profile> GetProfileInfo(string nick, string region)
        {
                var key = "RGAPI-56c986d1-1248-4f55-9545-d38117eb717d";
                var api = RiotApi.NewInstance(key);
                var summoner = await api.SummonerV4.GetBySummonerNameAsync(Region.Get(region), nick);
                var ranks = await api.LeagueV4.GetLeagueEntriesForSummonerAsync(Region.Get(region), summoner.Id);

            var SOLO = ranks.FirstOrDefault(qwerty => qwerty.QueueType == "RANKED_SOLO_5x5");
            var FLEX5V5 = ranks.FirstOrDefault(qwerty => qwerty.QueueType == "RANKED_FLEX_SR");
            var FLEX3V3 = ranks.FirstOrDefault(qwerty => qwerty.QueueType == "RANKED_FLEX_TT");

            var ranga5V5 = FLEX5V5.Tier + " " + FLEX5V5.Rank;
            var rangaSOLO = SOLO.Tier + " " + SOLO.Rank;
            var ranga3V3 = FLEX3V3.Tier + " " + FLEX3V3.Rank;
        }
```

**Comment by MingweiSamuel** [comment]
(Might need to regen your key now :D)
