### ISSUE TITLE
Some endpoints are expired

### ISSUE THREAD

**Issue by Taifunov** [MingweiSamuel/Camille#101]
![image](https://github.com/MingweiSamuel/Camille/assets/9999294/75530c24-4830-4a9f-9521-0bf7cf9a53db)

Can you please update endpoints with new params?

**Comment by MingweiSamuel** [comment]
https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2024-01-04-95741ea8f0

**Comment by Taifunov** [comment]
Hello, I updated the version but it still has summonnerId :/

![image](https://github.com/MingweiSamuel/Camille/assets/9999294/c344746e-6dce-4dc9-97d5-85ba1f49d984)
![image](https://github.com/MingweiSamuel/Camille/assets/9999294/cf7271b1-aafe-4727-bc2d-42bf031da15a)

**Comment by MingweiSamuel** [comment]
I’m away from my pc but definitely double check the versions, I think it should be there. Docs updated at least http://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.RiotGames.ChampionMasteryV4Endpoints.html#Camille_RiotGames_ChampionMasteryV4Endpoints_GetAllChampionMasteriesByPUUID_PlatformRoute_System_String_System_Nullable_System_Threading_CancellationToken__

**Comment by Taifunov** [comment]
You're right, for some reason were installed both old and new versions

**Comment by Taifunov** [comment]
@MingweiSamuel I'm not sure where exactly the issue is, but after the call to the endpoint get this error:
![image](https://github.com/MingweiSamuel/Camille/assets/9999294/95d29142-c730-4790-979f-e85e980185c2)

Can you please check it?

**Comment by AoshiW** [comment]
it looks like the enum [`QueueType`](https://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.Enums.QueueType.html) does not contain the value `CHERRY`

**Comment by Taifunov** [comment]
Yeah, in the result in the Riot API site I get this:
 "queueType": "CHERRY",
 
 But even with enum which is contains I got same issue

**Comment by MingweiSamuel** [comment]
@Taifunov What is the summoner name?

**Comment by Taifunov** [comment]
d3atomiz3d#RU1

**Comment by MingweiSamuel** [comment]
https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2024-01-04-674a80a9c0
version numbers went backwards unfortunately so you will need to manually select

**Comment by Taifunov** [comment]
Thanks, it fixed my issue!

**Comment by MingweiSamuel** [comment]
https://github.com/MingweiSamuel/riotapi-schema/issues/41

**Comment by MingweiSamuel** [comment]
Ok let me know if there’s any other issues!
