### ISSUE TITLE
`SpectatorV4().GetCurrentGameInfoBySummonerAsync` failing since 14.1 spectator changes

### ISSUE THREAD

**Issue by aPinat** [MingweiSamuel/Camille#102]
I _think_ it's just the GameType that is now different, not entirely sure if there is something else that might fail too.

`gameType` being different also in https://github.com/RiotGames/developer-relations/issues/878.

```System.Text.Json.JsonException: The JSON value could not be converted to Camille.Enums.GameType. Path: $.gameType | LineNumber: 0 | BytePositionInLine: 73.```

**Comment by MingweiSamuel** [comment]
From Riven
```
test spectator_combo ... error
RiotApiError {
    reqwest_error: reqwest::Error {
        kind: Decode,
        source: Error("unknown variant `TFT`, expected one of `UNKNOWN`, `ARAM`, `ARSR`, `ASCENSION`, `ASSASSINATE`, `CHERRY`, `CLASSIC`, `DARKSTAR`, `DOOMBOTSTEEMO`, `FIRSTBLOOD`, `GAMEMODEX`, `KINGPORO`, `NEXUSBLITZ`, `ODIN`, `ODYSSEY`, `ONEFORALL`, `PRACTICETOOL`, `PROJECT`, `SIEGE`, `STARGUARDIAN`, `TUTORIAL`, `TUTORIAL_MODULE_1`, `TUTORIAL_MODULE_2`, `TUTORIAL_MODULE_3`, `ULTBOOK`, `URF`", line: 1, column: 61),
    },
    retries: 0,
    response: None,
    status_code: Some(
        200,
    ),
}
```

**Comment by MingweiSamuel** [comment]
Getting
```
RiotApiError {
    reqwest_error: reqwest::Error {
        kind: Decode,
        source: Error("unknown variant `MATCHED`, expected one of `CUSTOM_GAME`, `MATCHED_GAME`, `TUTORIAL_GAME`", line: 1, column: 82),
    },
    retries: 0,
    response: None,
    status_code: Some(
        200,
    ),
}
```
as well

I will probably just update the code to parse those as the existing enum variants in lieu of adding new variants a la https://github.com/MingweiSamuel/riotapi-schema/pull/42

**Comment by aPinat** [comment]
Thanks!
Btw, RGAPI also returns PUUID nowadays for each participant, but the field isn't accessible here as Riot didn't update the schema.
Might be good to include, since that's needed for Riot ID lookup as well.

**Comment by MingweiSamuel** [comment]
Updated riotapi-schema, will be in the release

**Comment by MingweiSamuel** [comment]
https://www.nuget.org/packages/Camille.LolGame/3.0.0-nightly-2024-01-15-deb32a8340
http://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.RiotGames.SpectatorV4.Participant.html#Camille_RiotGames_SpectatorV4_Participant_Puuid
