### ISSUE TITLE
ChampionMasteryAPI

### ISSUE THREAD

**Issue by Taifunov** [MingweiSamuel/Camille#104]
![image](https://github.com/MingweiSamuel/Camille/assets/9999294/d372b474-ebe7-4dc6-b15b-c5ffeb93af9d)
Now it's required PUUID could you please replace old one with this?

**Comment by MingweiSamuel** [comment]
Is in the latest releases: [http://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.RiotGames.ChampionMasteryV4Endpoints.html#Camille_RiotGames_ChampionMasteryV4Endpoints_GetAllChampionMasteriesByPUUIDAsync_PlatformRoute_System_String_System_Nullable_System_Threading_CancellationToken__](http://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.RiotGames.ChampionMasteryV4Endpoints.html#Camille_RiotGames_ChampionMasteryV4Endpoints_GetAllChampionMasteriesByPUUIDAsync_PlatformRoute_System_String_System_Nullable_System_Threading_CancellationToken__)


https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2024-03-05-85cb341f01

Make sure you have the right version installed, lmk if theres any more trouble

**Comment by Taifunov** [comment]
For some reason it's still uses version 2.9.1-nightly-2022-06-03-b5cf263949 even if i updated to latest one :/

**Comment by MingweiSamuel** [comment]
That's the V2 version, package was renamed to `Camille.RiotGames` so you may need to uninstall the old one and install the new package

**Comment by Taifunov** [comment]
Yeah, this the issue, okay, thanks, now seems i have a lot of work :(
