### ISSUE TITLE
Camille.RiotGames.LeagueV4.LeagueEntry[] is null question

### ISSUE THREAD

**Issue by Chun-Pal-Kim** [MingweiSamuel/Camille#105]
Thank you for your help with my Discord bot development. 

However, I've encountered an issue where leagueV4 seems to be empty. 

When I use leaguev4 on the Riot developer website, I get results, but when I output it with Console.Write, only Camille.RiotGames.LeagueV4.LeagueEntry[] appears. 

Can you tell me how to solve this issue?

            var sumonor = riotApi.SummonerV4().GetByPUUID(PlatformRoute.KR, puuid);

            Console.WriteLine("summonorid : " + sumonor.Id);
            
            var league = riotApi.LeagueV4().GetLeagueEntriesForSummoner(PlatformRoute.KR, sumonor.Id);
            
            Console.WriteLine(league);

---------------------------------------------------------------------------------------------------------------

summonorid : iDiI8KXj_cOnyyL5jjlxvPl0zMsd61B8rn71596s6px1fTRfFefvecn-QA

Camille.RiotGames.LeagueV4.LeagueEntry[]

**Comment by AoshiW** [comment]
1. `SummonerId` and `Puuid` are encrypted per key/application so other people can't use them to test it (next time you have to send RiotId)
1. If it printed `Camille.RiotGames.LeagueV4.LeagueEntry[]` then it can't be `null`
1. Method returns an array - try to print individual elements of the array
```cs
foreach(var item in league)
{
    Concole.WriteLine(item);
}
```

**Comment by Chun-Pal-Kim** [comment]
foreach (var item in league)
            {
                if (item .QueueType == QueueType.RANKED_SOLO_5x5)
                {
                    Console.WriteLine(item .SummonerName);
                    Console.WriteLine($"{item .QueueType}");
                    Console.WriteLine($"{item .Rank}  {item .Tier}");
                    

                }
                
            }



thank you thank you
