### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by w00lfer** [MingweiSamuel/Camille#107]
Do you have any idea how could I mock RiotGamesApi class or HttpHandler inside of it for unit testing purposes?
I wanted to unit test my service class which creates instance of RiotGamesApi like this and then uses it to retrieve summoners, matches etc data
`private RiotGamesApi GetConfiguredRiotGamesApi(string riotApiKey)
    {
        var config = new RiotGamesApiConfig.Builder(riotApiKey).Build();
        return RiotGamesApi.NewInstance(config);
    }   ` 
    
My only idea is to create a "wrapper" around this class but tbh it's not best solution

**Comment by MingweiSamuel** [comment]
May be possible to use a mock server, now that #103/#108 is merged (will be in nightly release tonight)
