### ISSUE TITLE
Match Data - Participants - Challenges - BountyGold => Not Supported Format or Outside of Bounds for an Int32

### ISSUE THREAD

**Issue by Seiori** [MingweiSamuel/Camille#115]
Hello, wondering if anyone else is experiancing this issue. When attempting to grab the Match Data, in my case for Ranked Games (Queue Id: 420), am running into this error:

Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[System.Int32]. Path: $.info.participants[1].challenges.bountyGold | LineNumber: 0 | BytePositionInLine: 8938.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.

I have checked some Match Data responses from the Riot Games API manually, and in all cases the bountyGold seems to be simply 0.

**Comment by MingweiSamuel** [comment]
Fixed upstream but seems my Nuget API key expired so the change never got uploaded
https://github.com/MingweiSamuel/Camille/actions/runs/11676438628/job/32512687246

**Comment by MingweiSamuel** [comment]
Fixed in version `3.0.0-nightly-2024-11-09-a17f385bca` just released

**Comment by MingweiSamuel** [comment]
https://github.com/RiotGames/developer-relations/issues/1005
https://github.com/MingweiSamuel/riotapi-schema/commit/b05dc3aa13593c919de45a9b99ad9cd0992b741c
