### ISSUE TITLE
Support for System.Text.Json

### ISSUE THREAD

**Issue by RyadaProductions** [MingweiSamuel/Camille#12]
**Problem:** 
With the release of .NET Core 3.0 the default on ASP.NET Core web api's has become System.Text.Json instead of JSON.NET.
Due to this change, the library is not usable unless people manually add JSON.NET to their ASP.NET Core Project.

**Proposed solution:**
The changes required to have it working without any issues aren't too intrusive/breaking.

1. Use properties instead of fields for serialized json properties
2. Use object or something else instead of JObject in the additional properties.

These changes are only changes that need to be applied in the GeneratedClasses.cd.dt

**Comment by MingweiSamuel** [comment]
Merged!
