### ISSUE TITLE
New champions' names missing from Camille.Enums

### ISSUE THREAD

**Issue by nullkuhl** [MingweiSamuel/Camille#34]
Sett and Aphellios are missing from the list.

Current list

**Comment by MingweiSamuel** [comment]
The latest stable version, 2.4.1, is out of date. I should probably promote a nightly release to stable, but you can use [2.4.2-nightly-2020-02-18-01d413fe18](https://www.nuget.org/packages/MingweiSamuel.Camille/2.4.2-nightly-2020-02-18-01d413fe18) for now.

There is also a new version 3 on a different namespace which will be released eventually: https://www.nuget.org/packages/Camille.RiotApi/absoluteLatest

Does that solve the issue?

**Comment by nullkuhl** [comment]
I used version 3 from the nuget link you provided, did a few changes and its working fine now
