### ISSUE TITLE
[BUG] _AdditionalProperties does not work

### ISSUE THREAD

**Issue by AoshiW** [MingweiSamuel/Camille#41]

**Comment by MingweiSamuel** [comment]
Fix will be published in the next hour or so

Schema for TraitDto.style has updated https://github.com/MingweiSamuel/riotapi-schema/commit/f32acb677d94965c31f11cd8a82cf3ee0c78e4f9

**Comment by MingweiSamuel** [comment]
Fixed:
- 2.x.x https://www.nuget.org/packages/MingweiSamuel.Camille/2.6.2
- 3.x.x https://www.nuget.org/packages/Camille.RiotApi/3.0.0-nightly-2020-08-25-66352f1423
