### ISSUE TITLE
Change detection broken (Seraphine missing)

### ISSUE THREAD

**Issue by aPinat** [MingweiSamuel/Camille#47]
Currently the detection of changes seams to be broken again, as both the gh-pages branch and the newest NuGet nightly do not have Seraphine as new champion.

I'm creating a new issue copying my comment from #32 since I can't reopen it.

**Comment by MingweiSamuel** [comment]
Released https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2020-11-01-7045b7aeda w/ [Seraphine](http://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.Enums.Champion.html#fields) & the Division serialization bugfix. 

Still need a proper fix for the nightlies... reopening #32.

**Comment by aPinat** [comment]
New champion Rell is missing from both `gh-pages` and the latest build.

**Comment by MingweiSamuel** [comment]
Just manually triggered a new version. https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2020-12-12-fb192b268f
Thanks for letting me know
