### ISSUE TITLE
Not support all tournament api

### ISSUE THREAD

**Issue by jimkeecn** [MingweiSamuel/Camille#49]
Just found that the tournamentV4 endpoint only support a few,

apis like create tournamentCode, create Provider, create tournament are not implemented.

**Comment by MingweiSamuel** [comment]
For the non-GET endpoints you'll need to use the prerelease of version 3 of Camille: https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2020-12-12-fb192b268f

http://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.RiotGames.TournamentV4Endpoints.html#Camille_RiotGames_TournamentV4Endpoints_CreateTournamentCode_RegionalRoute_Camille_RiotGames_TournamentV4_TournamentCodeParameters_System_Int64_System_Nullable_System_Int32__System_Nullable_System_Threading_CancellationToken__

I'll try to properly stabilize it soon.
