### ISSUE TITLE
MingweiSamuel.Camille.Util.RiotResponseException: Request to match-v5.getMatchIdsByPUUID failed after 0 retries. (status: 400).

### ISSUE THREAD

**Issue by selmaohneh** [MingweiSamuel/Camille#55]
Hi!

I am trying to fetch some games with the new match-v5 endpoint.

![image](https://user-images.githubusercontent.com/29881939/126496834-719e41c0-20cd-490a-abc7-1792e25d968e.png)

Unfortunately I receive an error with Camille.

![image](https://user-images.githubusercontent.com/29881939/126497012-0397633a-0638-460b-acd9-b0c634bdfc1c.png)

Trying the same call from the Riot Developer Portal works as expected.

Any ideas?

**Comment by selmaohneh** [comment]
Tried with `2.8.0` and `2.8.1-nightly-2021-07-15-aaf8c5b8f7`

**Comment by AoshiW** [comment]
I may be wrong, but I think you're using the wrong region,
regions for MatchV5 are `Americas`,` Europe`, `Asia`
regions for SummonerV4 are `BR`, `EUNE`, `EUW` ....

**Comment by selmaohneh** [comment]
Ah... didn't know that. I'm gonna try that later. 
Confusing tho to have two different region when mixing calls from v4 and v5.

**Comment by selmaohneh** [comment]
That was it. Thanks!
