### ISSUE TITLE
Conversion between platform and regional routing values (Region)

### ISSUE THREAD

**Issue by selmaohneh** [MingweiSamuel/Camille#56]
Camille mixed platform routing values i.e. `RU` or `EUW1` with regional routing values i.e. `ASIA` or `EUROPE`. More on that can be found right here: https://developer.riotgames.com/docs/lol

Inside my application the `Region` is a setting that needs be configured once. Since I am mixing v4 and v5 calls I would need two settings - one for the regional and one for the platform routing value. 

I think splitting the `Region` struct into two separate structs is more clean!? Didn't think that trough tho ...

In order to avoid two settings one could also implement a converter method that would map these values in the direction regional --> platform. I am thinking of something likle `Region.ToPlatform()`? Or if you decide to split the struct something like `RegionalRouting.Euw1.ToPlatformRouting()`.

Any thoughts on that?

**Comment by MingweiSamuel** [comment]
I think version [3.x.x (in prerelease)](https://www.nuget.org/packages/Camille.RiotGames/) has this, is this what you are describing?
https://github.com/MingweiSamuel/Camille/blob/release/3.x.x/Camille.Enums/src/Route.cs

Seems ESPORTS is missing though, will have to add that.

**Comment by selmaohneh** [comment]
Looks like it. Nuget says that version is deprecated, so I installed the first one that looked a little bit more official to me.

![image](https://user-images.githubusercontent.com/29881939/126742065-48f762f6-1a2b-4346-b603-13d9ad5b9294.png)

[EDIT]
3.x.x does have the PlatformRoute, but is missing the MatchV5 endpoints. So they kind of diverged although I could use both.^^

Which one will be used in future? Can you clean that up?

Thanks in advance!

**Comment by AoshiW** [comment]
![image](https://user-images.githubusercontent.com/48525283/126752718-7f5c7bd0-1045-4822-a879-0ea060f753fb.png)

**Comment by selmaohneh** [comment]
Sometimes I am just blind. :D Thanks and sorry!
