### ISSUE TITLE
MatchV5().GetMatchAsync(...) throwing unhandled JsonException

### ISSUE THREAD

**Issue by selmaohneh** [MingweiSamuel/Camille#57]
Hi again,

I get an unhandled exception when calling the MatchV5.GetMatch endpoint.

![image](https://user-images.githubusercontent.com/29881939/126764343-20a1c6db-a721-4cdd-848d-2970aa855c7f.png)

This is the exception:

![image](https://user-images.githubusercontent.com/29881939/126764406-8c03cee4-d993-452e-9c68-8e37fbe76e16.png)

`gameCreation` seems to not be of type Int32?

Thoughts / fixes / workarounds?

**Comment by selmaohneh** [comment]
Further info:
* `RegionalRoute.EUROPE`
* MatchId is `EUW1_5378349967`

It works using the Riot Developer Portal.

Hope that helps.

**Comment by AoshiW** [comment]
`gameCreation`, `gameId`, `gameStartTimestamp`  should be `long`, not `int` and I assume this problem is in timeline endpoint as well. MingweiSamuel has to fix it.

**Comment by MingweiSamuel** [comment]
Thanks @AoshiW. Since Match-v5 is "dto descriptions soon™" I had to generate the schemas from examples and I didn't make a distinction between int and long (~~or float/double~~ actually aren't any floats), so it defaults to int32. I'll update those fields and add some tests

**Comment by MingweiSamuel** [comment]
> `gameCreation`, `gameId`, `gameStartTimestamp`

I changed these three to all be `long` and testing locally I was able to fetch `EUW1_5378349967`. There may be other fields that need to be upgraded to `long` so let me know if you encounter any errors like this.

Updated version is live here:  
https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2021-07-23-14aba191c9

**Comment by AoshiW** [comment]
`MatchInfoParticipant` contains 3 new field `turretTakedowns`, `nexusTakedowns`, `inhibitorTakedowns`

`RealTimestamp`, `GameId` => `long` in `MatchTimelineInfoFrameEvent`

**Comment by MingweiSamuel** [comment]
> `MatchInfoParticipant` contains 3 new field `turretTakedowns`, `nexusTakedowns`, `inhibitorTakedowns`

Hmm do those replace `turretKills`, `nexusKills`, and `inhibitorTakedowns`

> `RealTimestamp`, `GameId` => `long` in `MatchTimelineInfoFrameEvent`

Oh yeah completely forgot about timeline.

**Comment by AoshiW** [comment]
Why replace? They are "different" fields. And riot returns both.
Kill means... Kill
Takedown means kill + assist

**Comment by selmaohneh** [comment]
I'm fine with the recent changes from @MingweiSamuel - I'm gonna close the issue. Feel free to open a new issue for any related bugs.

Thanks a lot!
