### ISSUE TITLE
GetLeagueById returns code 400

### ISSUE THREAD

**Issue by LosSkillos** [MingweiSamuel/Camille#62]
![image](https://user-images.githubusercontent.com/63128140/139559413-d25ba49d-8d72-43ca-8e1e-0ffca7320da4.png)

**Comment by LosSkillos** [comment]
Just to clarify the "eun" thing is not the issue 
![image](https://user-images.githubusercontent.com/63128140/139559487-e9c9ffe4-a18d-4815-b398-f854118b8bc3.png)

**Comment by MingweiSamuel** [comment]
`GetByLeagueId` takes in a league UUID, `GetLeagueEntriesForSummoner(eun, summoner.Id)` is the method you want. Let me know if that works!

**Comment by LosSkillos** [comment]
That works, thanks.
