### ISSUE TITLE
inGameApi

### ISSUE THREAD

**Issue by RNGIllSkillz** [MingweiSamuel/Camille#66]
How to configure camille to get data from ingame api? can find any doc on that

**Comment by MingweiSamuel** [comment]
Sorry slipped through my notifications

This package: https://www.nuget.org/packages/Camille.LolGame/
Docs here: http://www.mingweisamuel.com/Camille/v/3.x.x/docs/api/Camille.LolGame.LiveClientData.html
Basic tests: https://github.com/MingweiSamuel/Camille/blob/release/3.x.x/Camille.LolGame.Test/LolGameTest.cs

Pretty straightforward to use no API key or anything needed:
```cs
LolGameApi Api = new LolGameApi();
var data = await Api.LiveClientData().GetAllGameDataAsync();
var gold = data.ActivePlayer.CurrentGold; // for example
...
```
