### ISSUE TITLE
How do I get the encrypted ID

### ISSUE THREAD

**Issue by LosSkillos** [MingweiSamuel/Camille#68]
So I have summoner ID in this form "2585765873935392" how do I get the encrypted version? Or this: "G9S9Zo2asfzLYFsJLw7Bdm3HaHWMbVbEGLT78wZoqCHgjvGoSagfwevudQ". Thanks

**Comment by MingweiSamuel** [comment]
Encrypted summoner ID is encrypted with a secret key attached to your Riot developer account that only Riot knows. This is to comply with some sort of privacy law (GDPR?).

The LCU (internal league client) APIs still use unencrypted IDs. So to get the encrypted summoner ID you first need to find the summoner name for the account, then use that to query [getBySummonerName](https://developer.riotgames.com/apis#summoner-v4/GET_getBySummonerName).

Info on the LCU here: https://hextechdocs.dev/getting-started-with-the-lcu-api/
Tool for working with LCU endpoints here: https://github.com/HextechDocs/lcu-explorer
