### ISSUE TITLE
GetThirdPartyCodeBySummonerIdAsync 403 error

### ISSUE THREAD

**Issue by Taifunov** [MingweiSamuel/Camille#85]
For now every time when i'm tying to get trird party code i get 403 error

**Comment by Stukeley** [comment]
I am also getting a 403 error, when trying to fetch Matchlist using `GetMatchListAsync`. Following the example from [README](http://www.mingweisamuel.com/Camille/v/2.6.3/docs/README.html). I tried with multiple development API keys, even borrowed one from a long-running app, but with no result.

**Comment by MingweiSamuel** [comment]
Third party code was deprecated in February and removed April 7. RSO is the replacement.

https://twitter.com/RiotGamesDevRel/status/1491217397965258752
https://twitter.com/RiotGamesDevRel/status/1499912431383945217
https://www.riotgames.com/en/DevRel/rso
