### ISSUE TITLE
lol ranks

### ISSUE THREAD

**Issue by kaaiss** [MingweiSamuel/Camille#9]
how i can get lol ranks like diamond 5 or bronze 3?

**Comment by MingweiSamuel** [comment]
Hi, you can do something like the following:

```c#
// Get summoner.
var summoner = riotApi.SummonerV4.GetBySummonerName(Region.EUW, "g2 perkz");
// Get league positions (all ranks).
var ranks = riotApi.LeagueV4.GetAllLeaguePositionsForSummoner(Region.EUW, summoner.Id);
// Find solo queue rank.
var soloRank = ranks.FirstOrDefault(r => r.QueueType == "RANKED_SOLO_5x5");
if (soloRank == null)
    Console.WriteLine("{0} is unranked.", summoner.Name);
else
    Console.WriteLine("{0} is {1} {2}.", summoner.Name, soloRank.Tier, soloRank.Rank);
```

It might be a little different for positional ranks though on NA or KR. Let me know if you'd like an example for that

**Comment by kaaiss** [comment]
thank you very much

**Comment by kaaiss** [comment]
one more question
how can i get ranks from flex queue?
should i change "RANKED_SOLO_5x5" to "RANKED_TEAM_5x5"?

**Comment by MingweiSamuel** [comment]
It's `"RANKED_FLEX_SR"`, not very user-friendly at the moment, on the todo list to get these strings somewhere obvious

(And if you're curious, 3v3s are `"RANKED_FLEX_TT"`)
