### ISSUE TITLE
Summoner.Puuid in SummonerV4 API Breaks Naming Convention

### ISSUE THREAD

**Issue by ElizabethDownum** [MingweiSamuel/Camille#95]
![image](https://user-images.githubusercontent.com/50033789/203777704-cb4d98b4-1512-4f34-b99d-1b674b1f3133.png)

All other variables are appended with "Id", whereas for puuid, it is "id".

Slightly confusing is all, very minor issue.

**Comment by MingweiSamuel** [comment]
With Camille I'm choosing to derive the names directly from the Riot API. In the JSON the "id" is also not capitalized in `puuid`.

<html><body>
<h5 id="1416-getBySummonerId-SummonerDTO" style="display: inline;">SummonerDTO </h5>
  
  - represents a summoner
  
  <br>
  

Name | Data Type | Description
-- | -- | --
accountId | string | Encrypted account ID. Max length 56 characters.
profileIconId | int | ID of the summoner icon associated with the summoner.
revisionDate | long | Date summoner was last modified specified as epoch  milliseconds. The following events will update this timestamp: summoner  name change, summoner level change, or profile icon change.
name | string | Summoner name.
id | string | Encrypted summoner ID. Max length 63 characters.
puuid | string | Encrypted PUUID. Exact length of 78 characters.
summonerLevel | long | Summoner level associated with the summoner.


</body>
</html>
