### ISSUE TITLE
CI failing -> no automatic updated builds -> missing newer additions/changes, e.g. K'Sante, new SEA regions

### ISSUE THREAD

**Issue by aPinat** [MingweiSamuel/Camille#96]
I'm probably a bit late with this, but I've now noticed the CI has been failing for a while, and seems to also have gotten auto-disabled by GitHub for inactivity, causing us to be missing additions/changes, like the K'Sante release from a few months back or this months new ex-Garena SEA regions.

**Comment by selmaohneh** [comment]
any updates on this?

**Comment by MingweiSamuel** [comment]
Fixed, nightly released now
https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2023-08-27-1f7c420fef
