### ISSUE TITLE
New GameMode not included in enum

### ISSUE THREAD

**Issue by EmanueleSpadaro** [MingweiSamuel/Camille#99]
Hi!
Riot in the latest patch, along with the release of Naafiri, released a new gamemode that makes RiotGamesApi.MatchV5().GetMatch() crash with an aggregate exception:
`One or more errors occurred. (The JSON value could not be converted to Camille.Enums.GameMode. Path: $.info.gameMode | LineNumber: 0 | BytePositionInLine: 854.)`.
An example match ID could be: `EUW1_6511808246`.

**Comment by VibrantClouds** [comment]
+1 on resolving this issue - Hitting the same issue. Your theory about there being new data that it can't deserialize seems pretty solid. Thanks for opening a PR!

**Comment by MingweiSamuel** [comment]
Fixed in latest nightly release
https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2023-08-27-1f7c420fef
